### ISSUE TITLE
Keep original case of table names

### ISSUE THREAD

**Issue by mnmami** [mnadeem/sql-table-name-parser#1]
This can be solved easily I guess by skipping the `toLowerCase()` from the code, but in general, it is better to keep the original letter case of the table names. If one wants later on to create a new SQL query using the extracted tables and execute it in a case-sensitive engine, then those tables can't be used as is without returning the original, which isn't practical.

**Comment by mnadeem** [comment]
Good Idea indeed... will change it

**Comment by mnadeem** [comment]
A new Version has been released

```
<dependency>
  <groupId>com.github.mnadeem</groupId>
  <artifactId>sql-table-name-parser</artifactId>
  <version>0.0.3</version>
</dependency>
```
