### ISSUE TITLE
second to last token being a comma leads to an infinite loop

### ISSUE THREAD

**Issue by gizem969** [mnadeem/sql-table-name-parser#4]
In a query of form "select xx from table1 a,table2 b" where there is a join with aliases but no join condition so that the second to last token is a comma, below code results in an infinite loop.

```
private void processAliasedMultiTables(final String[] tokens, int index, String currentToken) {
		String nextNextToken = null;
		if (moreTokens(tokens, index)) {
			nextNextToken = tokens[index++];
		}

		if (shouldProcessMultipleTables(nextNextToken)) {
			while (nextNextToken.equals(TOKEN_COMMA)) {
				if (moreTokens(tokens, index)) {
					currentToken = tokens[index++];
				}
				if (moreTokens(tokens, index)) {
					index++;
				}
				if (moreTokens(tokens, index)) {
					nextNextToken = tokens[index++];
				}
				considerInclusion(currentToken);
			}
		}
	} 
```

**Comment by mnadeem** [comment]
Thanks a bundle for pointing this out, I will look into this one

**Comment by mnadeem** [comment]
Fixed
@Test
	public void testSelectTwoTablesWithAliaseAndNoCondition() {
		String sql = "select xx from table1 a,table2 b";
		assertThat(new TableNameParser(sql).tables(), equalTo(asSet("table1", "table2")));
	}

**Comment by mnadeem** [comment]
0.0.5 release with the fix
